### ISSUE TITLE
Autofix-like UX instead of user interaction

### ISSUE THREAD

**Issue by slavingia** [gumroad/shortest#36]
; not sure if possible though…

**Comment by danthomps** [comment]
I'll probably look at this during the weekend. It's definitely possible but I'm fairly sure we have to would need to do polling in a vercel cron with a personal access token. Just have to be careful about rate limits.

I'm not sure we can reply to webhooks instantly without creating a bot, like the vercel one. But if we did that, then we'd have to have permissions to add it to every repo instead of being able to grab any and all PR's or issues on any repo, like we can now and committing under our own account.

[revise.dev](https://revise.dev) that Josh Pigford is working on takes the bot strategy in a similar product. So, to me, it seems like a core differentiator would be keeping it so the commits come from our own accounts so we can push changes anywhere
